/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#feb300",
        "primary-container": "#feb300",
        "primary": "#7a5400",
        "on-primary": "#fff1df",
        "on-primary-fixed": "#372400",
        "on-primary-container": "#523700",
        "primary-fixed-dim": "#eca600",
        "primary-dim": "#6b4900",
        "on-primary-fixed-variant": "#5e4000",
        "secondary": "#5c5b5b",
        "secondary-container": "#e5e2e1",
        "on-secondary": "#f5f2f1",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#d6d4d3",
        "secondary-dim": "#504f4f",
        "on-secondary-fixed": "#403f3f",
        "on-secondary-container": "#525151",
        "on-secondary-fixed-variant": "#5c5b5b",
        "tertiary": "#665c00",
        "tertiary-container": "#f8e54e",
        "tertiary-fixed": "#f8e54e",
        "tertiary-fixed-dim": "#e9d640",
        "tertiary-dim": "#595000",
        "on-tertiary": "#fff4b3",
        "on-tertiary-container": "#5c5200",
        "on-tertiary-fixed": "#474000",
        "on-tertiary-fixed-variant": "#665c00",
        "surface": "#f9f6f5",
        "surface-bright": "#f9f6f5",
        "surface-dim": "#d6d4d3",
        "surface-container": "#ebe7e7",
        "surface-container-low": "#f3f0ef",
        "surface-container-high": "#e5e2e1",
        "surface-container-highest": "#dfdcdc",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#dfdcdc",
        "surface-tint": "#7a5400",
        "on-surface": "#2f2e2e",
        "on-surface-variant": "#5c5b5b",
        "inverse-surface": "#0e0e0e",
        "inverse-on-surface": "#9e9c9c",
        "inverse-primary": "#feb300",
        "background": "#f9f6f5",
        "on-background": "#2f2e2e",
        "outline": "#787676",
        "outline-variant": "#afacac",
        "error": "#b02500",
        "error-container": "#f95630",
        "error-dim": "#b92902",
        "on-error": "#ffefec",
        "on-error-container": "#520c00",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
